// clients/angular-admin/src/app/app.component.ts
import { Component, OnInit } from "@angular/core";
import { CommonModule } from "@angular/common";
import { Router, RouterLink, RouterOutlet } from "@angular/router";
import { FormsModule } from "@angular/forms";
import { ButtonModule } from "primeng/button";
import { ToastModule } from "primeng/toast";
import { ConfirmDialogModule } from "primeng/confirmdialog";
import { AuthService } from "./core/auth.service";
import { ApiService, CLIENT_MODULES } from "./core/api.service";
import { TranslationService } from "./core/translation.service";
import { cultureCodeFromLanguageLookupRow, normalizeUiLanguage } from "./core/ui-language-code";
import { toLanguageOptions, type LanguageOption } from "./core/language-display";

@Component({
  selector: "app-root",
  imports: [CommonModule, FormsModule, RouterOutlet, RouterLink, ButtonModule, ToastModule, ConfirmDialogModule],
  templateUrl: "./app.component.html",
  styleUrl: "./app.component.scss"
})
export class AppComponent implements OnInit {
  readonly modules = CLIENT_MODULES;
  languageEntries: LanguageOption[] = toLanguageOptions(["tr-TR", "en-US"]);
  sidebarOpen = true;
  selectedLang = "tr-TR";
  darkMode = false;

  constructor(
    readonly authService: AuthService,
    readonly translationService: TranslationService,
    private readonly apiService: ApiService,
    private readonly router: Router
  ) {
    this.selectedLang = normalizeUiLanguage(this.authService.getLang());
    this.apiService.getByPath("/languages/codes").subscribe({
      next: (result) => {
        const list = Array.isArray(result) ? result : [];
        const codes = [
          ...new Set(
            list
              .map((item) => {
                const raw = cultureCodeFromLanguageLookupRow(item as Record<string, unknown>);
                return raw ? normalizeUiLanguage(raw) : null;
              })
              .filter((c): c is string => c != null && c !== "")
          )
        ];
        if (codes.length > 0) {
          this.languageEntries = toLanguageOptions(codes);
        }
      },
      error: () => {
        /* keep defaults */
      }
    });
    if (this.authService.isAuthenticated()) {
      this.translationService.load(this.authService.getLang()).subscribe();
    }
  }

  ngOnInit(): void {
    this.darkMode = localStorage.getItem("devarch.darkMode") === "true";
    document.documentElement.classList.toggle("app-dark", this.darkMode);
  }

  toggleDark(): void {
    this.darkMode = !this.darkMode;
    localStorage.setItem("devarch.darkMode", String(this.darkMode));
    document.documentElement.classList.toggle("app-dark", this.darkMode);
  }

  logout(): void {
    this.authService.logout();
    this.router.navigateByUrl("/login");
  }

  translate(key: string, fallback: string): string {
    return this.translationService.t(key, fallback);
  }

  toggleSidebar(): void {
    this.sidebarOpen = !this.sidebarOpen;
  }

  isActive(route: string): boolean {
    return this.router.url.startsWith(route);
  }

  navigate(route: string): void {
    this.router.navigateByUrl(route);
  }

  onLangChange(): void {
    this.selectedLang = normalizeUiLanguage(this.selectedLang);
    this.translationService.load(this.selectedLang).subscribe();
  }
}

<p-toast></p-toast>
<p-confirmDialog></p-confirmDialog>
<div class="layout-shell" [class.auth-layout]="authService.isAuthenticated()" [class.sidebar-collapsed]="authService.isAuthenticated() && !sidebarOpen">
  <header *ngIf="authService.isAuthenticated()" class="topbar">
    <div class="topbar-left">
      <button
        pButton
        type="button"
        icon="pi pi-bars"
        severity="secondary"
        [attr.title]="translate('action.menu', 'Menu')"
        (click)="toggleSidebar()"
      ></button>
      <h1>DevArchitecture</h1>
    </div>
    <div class="topbar-right">
      <label class="lang-select-wrap">
        <span class="visually-hidden">{{ translate("action.language", "Language") }}</span>
        <select
          class="lang-select"
          [(ngModel)]="selectedLang"
          (ngModelChange)="onLangChange()"
          [attr.aria-label]="translate('action.language', 'Language')"
        >
          <option *ngFor="let o of languageEntries" [value]="o.code">{{ o.flag }} {{ o.label }}</option>
        </select>
      </label>
      <button
        pButton
        type="button"
        severity="secondary"
        [rounded]="true"
        [icon]="darkMode ? 'pi pi-sun' : 'pi pi-moon'"
        [attr.title]="translate('action.toggleTheme', 'Toggle theme')"
        (click)="toggleDark()"
      ></button>
      <button
        pButton
        severity="secondary"
        icon="pi pi-sign-out"
        [attr.title]="translate('action.logout', 'Logout')"
        (click)="logout()"
      ></button>
    </div>
  </header>

  <aside *ngIf="authService.isAuthenticated()" class="side-nav" [class.collapsed]="!sidebarOpen">
    <div class="brand">Sakai</div>
    <button
      *ngFor="let item of modules"
      class="nav-link"
      [class.active]="isActive(item.route)"
      (click)="navigate(item.route)"
      [attr.title]="translate('menu.' + item.key, item.label)"
    >
      {{ translate('menu.' + item.key, item.label) }}
    </button>
  </aside>

  <main class="content-area">
    <router-outlet></router-outlet>
  </main>
</div>

// clients/vue-admin/src/App.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import Button from "primevue/button";
import Toast from "primevue/toast";
import ConfirmDialog from "primevue/confirmdialog";
import { CLIENT_MODULES } from "./config/modules";
import { apiClient, authStore } from "./services/api";
import { toLanguageOptions, type LanguageOption } from "./core/language-display";
import { cultureCodeFromLanguageLookupRow, normalizeUiLanguage } from "./core/ui-language-code";

const router = useRouter();
const isAuthenticated = computed(() => authStore.hasToken());
const sidebarOpen = ref(true);
const darkMode = ref(localStorage.getItem("devarch.darkMode") === "true");
const languageEntries = ref<LanguageOption[]>(toLanguageOptions(["tr-TR", "en-US"]));
const selectedLang = ref(normalizeUiLanguage(authStore.currentLang.value));

const menuLabel = (key: string, fallback: string) => {
  return authStore.t(`menu.${key}`, authStore.t(fallback, fallback));
};

const loadTopbarLanguages = async () => {
  try {
    const { data } = await apiClient.get("/languages/codes");
    if (!Array.isArray(data) || data.length === 0) {
      return;
    }
    const codes = [
      ...new Set(
        data
          .map((item: Record<string, unknown>) => {
            const raw = cultureCodeFromLanguageLookupRow(item);
            return raw ? normalizeUiLanguage(raw) : null;
          })
          .filter((c): c is string => c != null && c !== "")
      )
    ];
    if (codes.length > 0) {
      languageEntries.value = toLanguageOptions(codes);
    }
  } catch {
    /* keep defaults */
  }
};

const onLangChange = async () => {
  selectedLang.value = normalizeUiLanguage(selectedLang.value);
  await authStore.loadTranslations(selectedLang.value);
};

onMounted(async () => {
  await loadTopbarLanguages();
  selectedLang.value = normalizeUiLanguage(authStore.currentLang.value);
  if (authStore.hasToken()) {
    await authStore.loadTranslations();
  }
});

const logout = async () => {
  authStore.clearToken();
  await router.push("/login");
};

const toggleDark = () => {
  darkMode.value = !darkMode.value;
  localStorage.setItem("devarch.darkMode", String(darkMode.value));
  document.documentElement.classList.toggle("app-dark", darkMode.value);
};

const isActive = (route: string) => window.location.pathname.startsWith(route);
</script>

<template>
  <div class="layout-shell" :class="{ 'auth-layout': isAuthenticated, 'sidebar-collapsed': isAuthenticated && !sidebarOpen }">
    <Toast />
    <ConfirmDialog />
    <header v-if="isAuthenticated" class="topbar">
      <div class="topbar-left">
        <Button icon="pi pi-bars" severity="secondary" rounded :title="authStore.t('action.menu', 'Menu')" @click="sidebarOpen = !sidebarOpen" />
        <h1>DevArchitecture</h1>
      </div>
      <div class="topbar-right">
        <label class="lang-select-wrap">
          <span class="visually-hidden">{{ authStore.t("action.language", "Language") }}</span>
          <select
            v-model="selectedLang"
            class="lang-select"
            :aria-label="authStore.t('action.language', 'Language')"
            @change="onLangChange"
          >
            <option v-for="o in languageEntries" :key="o.code" :value="o.code">{{ o.flag }} {{ o.label }}</option>
          </select>
        </label>
        <Button
          :icon="darkMode ? 'pi pi-sun' : 'pi pi-moon'"
          severity="secondary"
          rounded
          :title="authStore.t('action.toggleTheme', 'Toggle theme')"
          @click="toggleDark"
        />
        <Button icon="pi pi-sign-out" severity="secondary" :title="authStore.t('action.logout', 'Logout')" @click="logout" />
      </div>
    </header>

    <aside v-if="isAuthenticated" class="side-nav" :class="{ collapsed: !sidebarOpen }">
      <div class="brand">Sakai</div>
      <button
        v-for="item in CLIENT_MODULES"
        :key="item.key"
        class="nav-link"
        :class="{ active: isActive(item.route) }"
        :title="menuLabel(item.key, item.label)"
        @click="router.push(item.route)"
      >
        {{ menuLabel(item.key, item.label) }}
      </button>
    </aside>

    <main class="content-area">
      <RouterView />
    </main>
  </div>
</template>
